### ISSUE TITLE
TODO Linux

### ISSUE THREAD

**Issue by looooo** [FreeCAD/FreeCAD_Conda#3]
- [x] update netgen builds (branch not working at the moment) try to (only python3)
- [x] update coin (fix redefinition of HAVE_INTTYPES_H)
- [x] update shiboken (removed, included in conda-forge pyside)
- [ ] build with centos to avoid stdc problems (also docker, maybe using condas gcc willl solve this)
- [x] coin download zipped (staged recipe)
