### ISSUE TITLE
[TODO] add qt5 support

### ISSUE THREAD

**Issue by looooo** [FreeCAD/FreeCAD_Conda#6]
- [ ] pyside2 available on conda-forge? official release?
- [x] update simage to qt5
- [x] coin, pivy with new simage
- [x] FreeCAD
